services:
  postgres_db:
    image: postgres:15-alpine
    container_name: ecosmart_postgres
    restart: always
    environment:
      POSTGRES_USER: ecosmart_admin
      POSTGRES_PASSWORD: ecosmart_secure_pass
      POSTGRES_DB: ecosmart_core
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
    networks:
      - ecosmart_network

  ecosmart_mailhog:
    image: mailhog/mailhog:latest
    container_name: ecosmart_mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - ecosmart_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ecosmart_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - ecosmart_network
    depends_on:
      - postgres_db

  redis:
    image: redis:7-alpine
    container_name: ecosmart_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ecosmart_network
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes

  redis-insight:
    image: redis/redisinsight:latest
    container_name: ecosmart_redis_insight
    restart: always
    ports:
      - "5540:5540"
    networks:
      - ecosmart_network
    depends_on:
      - redis

  backend_api:
    build: ./backend-api
    container_name: ecosmart_backend_api
    restart: always
    command: sh -c "
      until nc -z ecosmart_postgres 5432; do
        echo 'Waiting for Postgres...';
        sleep 2;
      done;
      until nc -z ecosmart_redis 6379; do
        echo 'Waiting for Redis...';
        sleep 2;
      done;
      npm run start:prod
      "
    ports:
      - "3000:3000"
    env_file:
      - ./backend-api/.env
    environment:
      SMTP_HOST: ecosmart_mailhog
      SMTP_PORT: 1025
      REDIS_HOST: ecosmart_redis
      REDIS_PORT: 6379
    networks:
      - ecosmart_network
    depends_on:
      - postgres_db
      - ecosmart_mailhog
      - redis

networks:
  ecosmart_network:
    driver: bridge